/* Legal content for the MeLun Hire marketing site footer. */
export const TERMS_SECTIONS: { title: string; body: string }[] = [
  { title: 'Acceptance of Terms', body: 'By accessing or using MeLun Hire, you agree to these Terms of Service and to comply with all applicable laws. If you do not agree, please do not use the service.' },
  { title: 'Description of Service', body: 'MeLun Hire is an AI-assisted hiring platform provided by MeLun that helps employers post roles, screen and evaluate applicants, conduct structured AI interviews, and review candidate reports. The service is provided as-is for its described purpose.' },
  { title: 'HR / Employer Responsibilities', body: 'Employers are responsible for the accuracy of the roles and requirements they publish, for making final hiring decisions, and for using candidate data lawfully. Employers must not use the platform to discriminate or to collect more candidate data than needed.' },
  { title: 'Applicant Responsibilities', body: 'Applicants agree to provide truthful information, complete interviews honestly, and not misuse the platform, another applicant data, or the interview process. Applicants are also responsible for keeping their account credentials safe.' },
  { title: 'Account Responsibilities', body: 'You are responsible for all activity under your account. Notify MeLun immediately if you believe your account or login details have been compromised.' },
  { title: 'AI-Assisted Hiring', body: 'MeLun Hire uses AI to assist with screening, matching, and evaluation. AI results are recommendations to support human decisions. MeLun Hire does not make employment decisions on its own and does not guarantee the accuracy of any model output.' },
  { title: 'Interview and Evaluation Process', body: 'Interviews and evaluations are delivered through the MeLun Hire platform and may include proctoring. MeLun Hire may record structured response data for reporting. Follow the platform requirements during an interview.' },
  { title: 'Data and Content', body: 'You are responsible for the content you submit. You grant MeLun the right to store and process that content to provide the service, including storing interview responses and generated reports.' },
  { title: 'Prohibited Use', body: 'You must not attempt to reverse engineer the service, upload malicious content, harvest user data, manipulate evaluation results, or otherwise interfere with the platform or other users.' },
  { title: 'Intellectual Property', body: 'The MeLun Hire platform, branding, and software remain the intellectual property of MeLun. You receive rights only to use the service for its intended purpose.' },
  { title: 'Service Availability', body: 'MeLun aims to keep the platform reliable but does not guarantee uninterrupted or error-free service. We may update, change, or suspend features to improve the product.' },
  { title: 'Limitation of Liability', body: 'MeLun Hire is provided as-is, without any guarantee of a specific outcome. To the extent permitted by law, MeLun is not responsible for decisions you make based on platform data or for indirect damages from normal service use.' },
  { title: 'Changes to Terms', body: 'We may revise these Terms from time to time. Continued use of the platform after changes take effect means you accept the updated Terms.' },
  { title: 'Contact Information', body: 'For questions about these Terms, contact us at hello@melun.ai.' },
];
export const PRIVACY_SECTIONS: { title: string; body: string }[] = [
  { title: 'Information We Collect', body: 'We collect the information you provide when you register and use the platform, including account details, application data, uploaded resumes, interview responses, and usage data needed to operate the service.' },
  { title: 'Applicant Information', body: 'We collect the profile and account details applicants provide when they register, such as name, contact details, and professional background.' },
  { title: 'Resume and Application Data', body: 'When you submit a resume or apply to a role, we process and store that data so it can be evaluated and matched to relevant positions.' },
  { title: 'Interview Data', body: 'Interview responses and evaluation data are stored so the platform can generate reports and let HR review candidates. Proctoring may collect session signals.' },
  { title: 'HR / Employer Data', body: 'We collect the information HR and employer accounts provide, including company profile details, job posts, notifications, and hiring activity used to operate the platform.' },
  { title: 'How We Use Information', body: 'We use information to provide, maintain, and improve the MeLun Hire platform, to process applications and interviews, to generate evaluation reports, and to tailor the experience to your role.' },
  { title: 'AI Processing', body: 'Submitted content is processed by MeLun Hire AI features to parse resumes, match candidates, and evaluate interview responses. This processing is part of the service you are using.' },
  { title: 'Data Sharing', body: 'We share data minimally so the platform functions, such as sharing candidate materials with the employers reviewing them. We do not sell personal information beyond what is needed.' },
  { title: 'Data Storage', body: 'Data is stored on servers we operate or manage as part of the MeLun Hire platform. Some appearance and settings preferences are kept locally in your browser to improve the experience.' },
  { title: 'Security', body: 'We take reasonable steps to secure the information we hold, including protected credential handling, but no service can guarantee absolute security.' },
  { title: 'Cookies / Local Storage', body: 'The platform may use browser cookies and local storage to remember your session and preferences. You can clear local storage through your browser settings.' },
  { title: 'User Choices and Rights', body: 'You can request access to, correction of, or removal of the information MeLun holds about you, where supported, by contacting us. You may also choose to limit what you share.' },
  { title: 'Data Retention', body: 'We retain data while it is needed to operate the platform and provide reports, and remove it when it is no longer required for the service.' },
  { title: 'Contact Information', body: 'For privacy questions, contact us at hello@melun.ai.' },
  { title: 'Policy Updates', body: 'If we change how we collect or use information, we will update this page. Continued use of the platform means you accept the current policy.' },
];